### ISSUE TITLE
gnvim_lsp#hover#cursor_moved => unknown function gnvim#cursor_tooltip#hide

### ISSUE THREAD

**Issue by teto** [vhakulinen/gnvim#33] opened 2019-04-26 04:57 UTC
for some reason I can't select the text in messages but basically with neovim master and gnvim_lsp plugin I get ` unknown function gnvim#cursor_tooltip#hide`

**Comment by teto** [comment] 2019-04-26 04:58
more details:
```
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: pumblend
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_multigrid
Not supported option set: ext_hlstate
Not supported option set: ext_termcolors
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
Not supported option set: termguicolors
Received unknown redraw event: mouse_on
Received unknown redraw event: set_icon
Received unknown redraw event: update_menu
Not supported option set: termguicolors
Received unknown redraw event: update_menu
Received unknown redraw event: mouse_on
Not supported option set: showtabline
Received unknown redraw event: mouse_off
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Failed to turn input event into nvim key (keyval: 65513)
Received unknown redraw event: mouse_on
Received unknown redraw event: set_icon
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_messages
Received unknown redraw event: mouse_off
Received unknown redraw event: mouse_on
Received unknown redraw event: mouse_off
Received unknown redraw event: mouse_on
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
GnvimScroll error: NeovimError(0, "Vim(call):E117: Fonction inconnue : gnvim#cursor_tooltip#hide")
Received unknown redraw event: mouse_on

```

**Comment by vhakulinen** [comment] 2019-04-28 09:35
`gnvim#cursor_tooltip#hide` is defined [here](https://github.com/vhakulinen/gnvim/blob/d1b19d6169c06507e9a6c8f9755064b6772b32b9/runtime/autoload/gnvim/cursor_tooltip.vim#L33). Make sure that `GNVIM_RUNTIME_PATH` is pointing to correct place so gnvim can load it's runtime files.

**Comment by teto** [comment] 2019-04-28 12:03
I can fix GNVIM_RUNTIME_PATH as you say. Do you plan to add an installer that would properly install this ? for instance I don't think neovim-qt requires anything for 
https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim

**Comment by vhakulinen** [comment] 2019-04-28 12:11
`gnvim` requires some colors from color scheme which nvim can't supply (currently) without some custom viml and I don't fancy too much to include that viml into the binary it self. The `Makefile` contains instructions for `make install` to [copy](https://github.com/vhakulinen/gnvim/blob/d1b19d6169c06507e9a6c8f9755064b6772b32b9/Makefile#L19) the files in place.

The default value for `GNVIM_RUNTIME_PATH` is defined [here](https://github.com/vhakulinen/gnvim/blob/d1b19d6169c06507e9a6c8f9755064b6772b32b9/src/main.rs#L58). If you need that to be different, any PRs to define that value on compile time are welcome. Shouldn't be much different from how we currently define the version number.

I'm closing this issue, since from what I gathered, the issue is/was that you had `GNVIM_RUMTIME_PATH` set to wrong value.

**Closed by vhakulinen** 2019-04-28 12:11 UTC

**Comment by teto** [comment] 2019-04-29 16:04
> The default value for GNVIM_RUNTIME_PATH is defined here. If you need that to be different, any PRs to define that value on compile time are welcome. Shouldn't be much different from how we currently define the version number.

I wrapped the program with a correct value for GNVIM_RUNTIME_PATH, reinstalled the lsp program and it seems to work though I don't get markdown popups. I guess I must use the vim-lsp plugin. Anyway I could adapt it to LanguageClient-neovim ?

**Comment by vhakulinen** [comment] 2019-04-30 16:49
Gnvim provides API for using the cursor tooltip, which [gnvim-lsp](https://github.com/vhakulinen/gnvim-lsp) uses to do the hover using lsp and the vim-lsp vim plugin. The code that handles the hover stuff is quite trivial ([here](https://github.com/vhakulinen/gnvim-lsp/blob/f137b5362dab3c1897c76f50f761e59411effc78/autoload/gnvim_lsp/hover.vim)). Most of the code is for handling the cursor tooltip position. Porting that to use LangaugeClient-neovim should be quite trivial.
