### ISSUE TITLE
Black screen / no titlebar

### ISSUE THREAD

**Issue by scotty531** [vhakulinen/gnvim#220] opened 2024-03-10 05:24 UTC
When I open the program I get a black screen and a titlebar with a black rectangle in it. I'm using nvim 0.9.5 with gnvim installed from the Arch AUR. When I build it from source the editor shows up but it looks the same as before.

This is the result of RUST_BACKTRACE=full

`
(gnvim:971421): gnvim-WARNING **: 05:02:37.153: grid 3 not found in ui/src/components/shell/mod.rs:303
thread 'main' panicked at ui/src/components/appwindow/imp.rs:78:26:
failed to decode redraw notification: Syntax("error while decoding value: invalid length 5, expected fewer elements in array")
stack backtrace:
   0:     0x5dbecf472976 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5dbecf472976 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5dbecf472976 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5dbecf472976 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5dbecf498970 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x5dbecf498970 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x5dbecf4709ef - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x5dbecf472754 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5dbecf472754 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5dbecf473cb7 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x5dbecf473a19 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x5dbecf474148 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x5dbecf474022 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x5dbecf472e76 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5dbecf473d80 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x5dbecf311ee5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x5dbecf312393 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x5dbecf356df8 - core::result::Result<T,E>::expect::h06611933d2c771bb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
  18:     0x5dbecf356df8 - gnvim::components::appwindow::imp::AppWindow::process_nvim_event::{{closure}}::h4d8ca5e4ce96e1cd
                               at /usr/src/debug/gnvim/gnvim-0.3.1/ui/src/components/appwindow/imp.rs:77:34
  19:     0x5dbecf356df8 - gnvim::components::appwindow::imp::AppWindow::io_loop::{{closure}}::h2ddf514ab7231fab
                               at /usr/src/debug/gnvim/gnvim-0.3.1/ui/src/components/appwindow/imp.rs:106:57
  20:     0x5dbecf356df8 - <gnvim::components::appwindow::imp::AppWindow as glib::subclass::object::ObjectImpl>::constructed::{{closure}}::h99aa972cb5c1d6dc
                               at /usr/src/debug/gnvim/gnvim-0.3.1/ui/src/components/appwindow/imp.rs:604:39
  21:     0x5dbecf356df8 - glib::main_context_futures::<impl glib::auto::main_context::MainContext>::spawn_local_with_priority::{{closure}}::h11cca136acfbb60a
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context_futures.rs:564:24
  22:     0x5dbecf455222 - <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll::h5a2d077d2bf5f6c6
  23:     0x5dbecf455222 - glib::main_context_futures::TaskSource::poll::{{closure}}::{{closure}}::h3f936c6e8596b4fc
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context_futures.rs:245:25
  24:     0x5dbecf455222 - core::ops::function::FnOnce::call_once::h82fc61af76633607
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  25:     0x5dbecf455222 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h997d5ea7a85fefb2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  26:     0x5dbecf455222 - std::panicking::try::do_call::h00b1f2e49ba4fe51
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  27:     0x5dbecf455222 - std::panicking::try::h22743ddf37bf07a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  28:     0x5dbecf455222 - std::panic::catch_unwind::h253339f38f9a13bf
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  29:     0x5dbecf455222 - glib::main_context_futures::TaskSource::poll::{{closure}}::h33d4d12133cf8635
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context_futures.rs:244:31
  30:     0x5dbecf455222 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h68fcfb0731c26f11
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context.rs:154:12
  31:     0x5dbecf450f31 - glib::main_context_futures::TaskSource::poll::h35afbbc7311c5c13
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context_futures.rs:236:9
  32:     0x5dbecf450f31 - glib::main_context_futures::TaskSource::dispatch::h46212f9e62a757dc
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.5/src/main_context_futures.rs:74:34
  33:     0x75b3a6801f69 - <unknown>
  34:     0x75b3a68603a7 - <unknown>
  35:     0x75b3a6800162 - g_main_context_iteration
  36:     0x75b3a69d3b66 - g_application_run
  37:     0x5dbecf388df6 - <O as gio::application::ApplicationExtManual>::run_with_args::h08d9aef1057b5fb8
                               at /home/scotty/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.17.4/src/application.rs:37:13
  38:     0x5dbecf32d41a - gnvim::main::h64a5bfce7b429ff1
                               at /usr/src/debug/gnvim/gnvim-0.3.1/ui/src/main.rs:41:5
  39:     0x5dbecf37a5a3 - core::ops::function::FnOnce::call_once::ha5e3a0c9017633b4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  40:     0x5dbecf37a5a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h438f46926349014c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  41:     0x5dbecf37a5b9 - std::rt::lang_start::{{closure}}::hb304baa4e1f7cc95
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  42:     0x5dbecf46cb61 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  43:     0x5dbecf46cb61 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  44:     0x5dbecf46cb61 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  45:     0x5dbecf46cb61 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  46:     0x5dbecf46cb61 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  47:     0x5dbecf46cb61 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  48:     0x5dbecf46cb61 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  49:     0x5dbecf46cb61 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  50:     0x5dbecf46cb61 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  51:     0x5dbecf32d4fc - main
  52:     0x75b3a64ffcd0 - <unknown>
  53:     0x75b3a64ffd8a - __libc_start_main
  54:     0x5dbecf312655 - _start
  55:                0x0 - <unknown>
`

**Comment by vhakulinen** [comment] 2024-03-10 12:52
Probably duplicate of #214. Are you sure you're running the latest version of gnvim?

**Closed** 2024-03-19 07:43 UTC
