### ISSUE TITLE
scrolloff setting cases line rendering problems

### ISSUE THREAD

**Issue by japorized** [vhakulinen/gnvim#63] opened 2019-07-05 22:49 UTC
Hi there,

I'm getting rendering issues that I'm not sure how to exactly describe what I saw in words.

## How to reproduce

1. `gnvim -- -u NONE`
2. Open up document longer than your screen height.
3. `:set scrolloff=999`
4. Scroll to a location your cursor is in the middle of the screen area.
5. Hit `o` and hit Enter a few times.

## Other notes

1. This does not happen if one has `set number`. I reckon that the reason is cause the lines are redrawn to render the line numbers and so it shadows the problem.

#### gnvim version -- 0.1.3

**Comment by smolck** [comment] 2019-07-06 02:41
Able to reproduce. Have you gotten this issue when using gnvim normally (i.e. without the `-- -u NONE` args)?

**Comment by japorized** [comment] 2019-07-06 04:55
Yes. I had the `-- -u NONE` as a minimal working example.

I also tried to see if this happens for different files, like a simple text file and a LaTeX file, to kind of see if syntax highlighting mattered. The visual glitch happened in both cases.

Granted, it’s just a visual glitch. Scrolling up/down away from where the glitch occurs and coming back makes gnvim re-render correctly.

On Jul 5, 2019, at 22:41, smolck <notifications@github.com<mailto:notifications@github.com>> wrote:


Able to reproduce. Have you gotten this issue when using gnvim normally (i.e. without the -- -u NONE args)?

**Comment by vhakulinen** [comment] 2019-07-08 16:50
I can reproduce this. For further reference, you should use empty vimrc file instead of `-uNONE` when testing gnvim since `-uNONE` prevents gnvim from loading its own runtime files.

This sounds like a bug in neovim it self, especially since `set number` affects it - and probably some other options too since after setting `nonumber`, I couldn't reproduce this with my init.vim. It would be noteworthy to test this with other GUIs.

CC: @bfredl

**Comment by bfredl** [comment] 2019-07-08 17:25
The issue seems to be that a too large area is scrolled. Which is weird, as TUI should use exactly the same scrolling events (and it works there).

**Comment by smolck** [comment] 2019-07-08 20:28
> It would be noteworthy to test this with other GUIs.

In both Gonvim and neovim-gtk scrolling stopped entirely when the cursor reached the scroll limit at the bottom of the screen when I tested it (so I was holding `Enter` and the text on screen didn’t move down at all).

**Comment by japorized** [comment] 2019-07-08 21:13
Tested with nvim-qt as well and no problems there.

Also tried @vhakulinen's suggestion of using an empty vimrc for testing. Same visual glitch occurs.

**Comment by smolck** [comment] 2019-07-13 21:56
It seems this is caused by GNvim not handling all of the grid_scroll events it’s given from Neovim, and so it should be fixed in #72 (currently #72 does fix the problem, but it’ll probably need some refining if it’s gonna be merged).

**Closed** 2019-07-17 19:00 UTC
