### ISSUE TITLE
"wildmenu" is not available when --disable-ext-cmdline

### ISSUE THREAD

**Issue by cohama** [vhakulinen/gnvim#80] opened 2019-07-19 01:33 UTC
Confirmed minimal step.
1. `gnvim --disable-ext-cmdline -- -u NONE`
2. `:set wildmenu`  (maybe unnecessary)
3. `:set wildmode=full` (maybe unnecessary)
4. type `:a<Tab>` but wild menu will not appear.

My gnvim/nvim version is below.
- gnvim 0.1.4-18-gef64282
- nvim NVIM v0.4.0-738-g8330cc22a

**Comment by smolck** [comment] 2019-07-19 02:17
@cohama Can you try running this with a commented out `.vimrc`/`init.vim` instead? Using `-- -u NONE`/`-- -u NORC` prevents GNvim from loading its runtime files, which I think is what's causing this problem. When I used a commented out `init.vim` instead, I wasn't able to reproduce this issue when using GNvim with `--disable-ext-cmdline`. Do you have this problem when running GNvim like this: `$ gnvim --disable-ext-cmdline`?

@vhakulinen Do you think we should provide an alternative to `-- -u NONE` that would ignore the user's init.vim/.vimrc but still load GNvim's runtime files (for debugging purposes)? Alternatively, we could find a way to still load GNvim's runtime files when it's passed `-- -u NONE` if that's possible. It seems that the above is a recurring issue that causes users to think problems exist that don't (or at least leads them astray when debugging).

**Comment by cohama** [comment] 2019-07-19 02:42
wildmenu appeared with a commented out `init.vim`!

**Comment by cohama** [comment] 2019-07-19 02:54
I expect wildmenu is like CUI.
![image](https://user-images.githubusercontent.com/348382/61505910-6cefbb00-aa1b-11e9-8466-486bb6387fa1.png)

I also noticed that wildmenu dissapeared again with `--disable-ext-popupmenu`

In detail, with commented out `init.vim`, then run `gnvim --disable-ext-cmdline --disable-ext-popupmenu`

Is this by design?

**Comment by smolck** [comment] 2019-07-19 03:30
No, I think this is a bug. This only happens if both the ext_cmdline and the ext_popupmenu are disabled (AFAIK). GNvim currently doesn't seem to support that combination. Since the wildmenu is tied to the popupmenu, it makes sense why the GUI version of the wildmenu wouldn't appear when the popupmenu is disabled, but when not external I think nvim takes care of the wildmenu (so GNvim isn't showing it for some reason).

CC: @vhakulinen

**Comment by vhakulinen** [comment] 2019-07-24 17:35
There is a `ext_wildmenu` UI option on nvim 0.3.x, but that was incorporated into `ext_popupmenu` on 0.4.x, so thats why you need to disable _both_ popupmenu and cmdline. For clarity, we should add a flag for the wildmenu too: https://github.com/vhakulinen/gnvim/blob/1d8a0425b851cd4cb821c38ac2b6a50c6b52fd07/src/main.rs#L131 and improve documentation regarding the change between nvim 0.3 and 0.4.

>  Do you think we should provide an alternative to -- -u NONE that would ignore the user's init.vim/.vimrc but still load GNvim's runtime files (for debugging purposes)?

We should probably add a minimal vimrc into the readme. I've seen that quite a few vim plugins does that. If we pass `-u NONE` to nvim, it wont load _any_ runtime files.

**Comment by last-partizan** [comment] 2020-08-18 20:14
Right now wildmenu works when both cmdline and popupmenu are disabled. But it is at wrong position.

![image](https://user-images.githubusercontent.com/301015/90560627-14539a00-e1a8-11ea-9317-54ebba62f910.png)

**Comment by nikplx** [comment] 2021-07-18 12:47
I can't reproduce this issue with the latest master version anymore.
 @last-partizan @vhakulinen Can we close this issue?

![wildmenu_right](https://user-images.githubusercontent.com/42221768/126067613-b3d6ddff-a626-4cc9-bdb3-40428e7474db.png)

**Comment by last-partizan** [comment] 2021-07-18 13:03
Yes, i think this can be closed.

Menu positioning was wrong becouse neovim bug, and not it is fixed.

**Closed** 2022-11-27 13:11 UTC
