### ISSUE TITLE
Changes silently lost if the editor window is closed

### ISSUE THREAD

**Issue by alexeymuranov** [vhakulinen/gnvim#182] opened 2021-10-31 09:15 UTC
If i close the editor window with window close button, the changes in the open buffers are silently lost.

**Comment by maage** [comment] 2021-11-05 15:44
You can fix this with configuration.

Add: ~/.config/nvim/init.vim
```
set autowriteall
```
Or if you want to protect against crashes too, also add:
```
augroup AUTOSAVE
  au!
  autocmd InsertLeave,TextChanged,TextChangedI,FocusLost * silent! write
augroup END
```

From `:h 'autowriteall'`
```
'autowriteall' 'awa'    boolean (default off)
                        global
        Like 'autowrite', but also used for commands ":edit", ":enew", ":quit",
        ":qall", ":exit", ":xit", ":recover" and closing the Vim window.
        Setting this option also implies that Vim behaves like 'autowrite' has
        been set.
```

**Comment by alexeymuranov** [comment] 2021-11-05 16:18
Thanks, this is better than nothing, but I would expect a confirmation dialogue to appear. Maybe changes were unintentional.

**Comment by alexeymuranov** [comment] 2021-11-06 09:14
If implementing confirmation dialogue is not yet planned, I think an acceptable workaround is to disable the window close button.

**Comment by dbarnett** [comment] 2022-06-19 00:10
Same as #147?

**Comment by vhakulinen** [comment] 2022-11-27 12:24
Duplicate of #147.

**Closed by vhakulinen** 2022-11-27 12:24 UTC
