### ISSUE TITLE
feedback & quit_confirm feature request

### ISSUE THREAD

**Issue by tobealive** [vhakulinen/gnvim#189] opened 2022-05-07 23:38 UTC
Hello,

A little additional data safety feature I think would be awesome is triggering a quit_confirm when OS-closing the window. Causing a prompt when trying to close the client while having unsaved buffers. Maybe as an option or the default behavior. What do you think about such a thing?

And I'm coincidentally seeing the good news that it'll be ported to gtk4. Man, thanks for developing such a great client! What I always liked most about gnvim that it had the most flawless implementation of smooth scrolling. Coconut oily smooth animations and no jumpiness when scrolling over folds. Makes it a pleasure to use. Imho none of the other nvim UIs can compete with this. 

Sending love and blessings

**Comment by vhakulinen** [comment] 2022-05-08 10:06
Would sending `:qa` to nvim when you press the close button do the trick? I think that would be the "correct" thing to do.

And thank you for the kind words.

**Comment by tobealive** [comment] 2022-05-08 11:33
Hello, 
Nice to read your reply. Yes, that's what I thought of! System-closing a window I usually do with meta+q. A workaround I tried to achieve this, was to integrate the gdk superkey modifier into the modifier keylist and then to map this comb inside vim to `:qa`. Unfortunately that didn't work out. Also, this is probably more complicated than what it needs to be for this simple purpose.

**Comment by dbarnett** [comment] 2022-06-19 00:11
Looks like confirm on close was previously requested in #147.

**Comment by tobealive** [comment] 2022-06-19 08:21
> Looks like confirm on close was previously requested in #147.

Oh, exactly. Must have missed that. And like you mentioned in the other issues there are multiple of those requests. 
Hope it gets implemented soon. Unfortunately I currently don't have the time to work my way into how to apply that into the window close event.

**Comment by vhakulinen** [comment] 2022-11-27 11:43
Closing as duplicate of #147.

**Closed by vhakulinen** 2022-11-27 11:43 UTC
