### ISSUE TITLE
Status line is cut, sometimes not visible at all

### ISSUE THREAD

**Issue by sebastien** [vhakulinen/gnvim#120] opened 2019-10-30 22:04 UTC
Here is an example:

![image](https://user-images.githubusercontent.com/14598/67902509-386ccd00-fbce-11e9-9b9a-de49e608005c.png)

I can manage to get the status line fully visible by adjusting the window height, but you need to be very precise. Maybe snapping the window height to increments of the displayed line height would solve the problem?

**Comment by smolck** [comment] 2019-10-31 01:57
Thanks for reporting this issue! What is your pango version, Neovim version, and Gnvim version?

**Comment by sebastien** [comment] 2019-10-31 04:07
@smolck I'm using Fedora 31, pango-1.44.6-1, neovim-0.4.2-1 and gnvim from source at 16b465b967533386f380a1696b9f7c7b9b89e77e

**Comment by vhakulinen** [comment] 2019-10-31 07:54
Pango 1.44 is currently quite problematic (see #85). Are you not experiencing any other rendering problems (blurry font, scrolling problems or invalid cursor position)?

**Comment by sebastien** [comment] 2019-10-31 20:47
@vhakulinen Yes, the blurring on scroll for sure -- but I didn't have that with nvim-gtk, though.

**Comment by smolck** [comment] 2019-10-31 22:45
I don’t believe nvim-gtk has the scrolling issue, mostly text-related ones (GNvim has similar issues in addition to this one and the scrolling issue). If I correctly recall a chat on the Neovim gitter, @ford-prefect had GNvim issues on Fedora too, since Fedora now has latest (or basically latest) pango.....

Anyways, this is probably a duplicate of #85.

**Comment by vhakulinen** [comment] 2019-11-01 07:53
Based on information given here, I'll mark this as duplicate of #85.

**Closed by vhakulinen** 2019-11-01 07:53 UTC
